# Generated by Django 4.2.3 on 2023-08-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='pinterest_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='playstore_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='youtube_url',
        ),
    ]
