# Generated by Django 4.2.4 on 2023-09-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
