# Generated by Django 4.2.5 on 2023-10-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photo_microsoftteam_url_photo_zoom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='microsoftTeam_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pinterest_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='playstore_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='website_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='zoom_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
