# Generated by Django 4.2.5 on 2023-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_broker_microsoftteam_url_broker_zoom_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
