# Generated by Django 4.2.4 on 2023-09-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='logo',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
