# Generated by Django 4.2.5 on 2023-09-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0003_filelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='microsoftTeam_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='zoom_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
